spring:
  #???
  application:
    name: service-edu
  #????
  profiles:
    active: dev
  #mysql?????
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456